import { InfoPage } from '../../components/info-page';
import { contentMetadata } from '../../content/metadata';
export const metadata = contentMetadata('/privacy', 'en', 'Privacy policy', 'How Puzzly handles searches, puzzle progress, external images, cookies, and advertising.');
export default function Page() {
  return <InfoPage locale="en" path="/en/privacy" eyebrow="PRIVACY" title="Privacy policy" intro="This English version explains the same practices as our Korean policy. Effective August 27, 2026; English translation added September 14, 2026.">
    <section><h2>1. Information we collect</h2><p>Puzzly does not offer account registration or directly collect and store names, telephone numbers, or addresses through registration forms. Image search terms are processed temporarily to recommend images, but are not stored in a Puzzly user account or database. The selected image, piece count, and puzzle progress are handled in your browser.</p></section>
    <section><h2>2. Information sent automatically</h2><p>When you access the site, hosting and external content providers may receive ordinary connection information such as your IP address, browser type, access time, and requested URL. They may process this information for security, troubleshooting, content delivery, and operation of their services.</p></section>
    <section><h2>3. External image services</h2><p>Images come from the Pexels search API and Unsplash images selected for the service. When you search, your query passes through Puzzly to Pexels. Displaying images may send requests to Pexels or Unsplash servers. Their privacy policies may apply; Puzzly does not control their data processing.</p></section>
    <section><h2>4. Cookies and advertising</h2><p>Puzzly uses Google AdSense and Kakao AdFit scripts for site verification and advertising. Google, Kakao, and their advertising partners may use cookies or similar technologies and process IP addresses, browser information, advertising identifiers, and access or advertising interaction records to deliver ads, measure impressions and clicks, prevent fraud, and personalize advertising. Puzzly itself does not set a separate required cookie for puzzle progress.</p><p>You can manage or disable personalized Google advertising in <a href="https://adssettings.google.com/" target="_blank" rel="noreferrer">Google Ad Settings</a>. You can also manage participating third-party advertising cookies through <a href="https://www.aboutads.info/choices/" target="_blank" rel="noreferrer">AboutAds choices</a>. See <a href="https://kakao.com/policy/privacy" target="_blank" rel="noreferrer">Kakao’s privacy policy</a> and <a href="https://adfit.kakao.com/" target="_blank" rel="noreferrer">Kakao AdFit</a> for their practices and available choices.</p></section>
    <section><h2>5. Retention and deletion</h2><p>Puzzly does not retain your searches or puzzle progress in its own database. Progress in browser memory is lost when you close or refresh the page. Hosting and external service logs are managed under each provider’s retention policy.</p></section>
    <section><h2>6. Children’s information</h2><p>Puzzly does not verify users’ ages or intentionally collect children’s personal information. Parents and guardians should supervise children’s use of external links and image services.</p></section>
    <section><h2>7. Changes and contact</h2><p>This policy may change when features or applicable requirements change, with an updated effective date. Contact <a href="mailto:daehoon1027@gmail.com">daehoon1027@gmail.com</a> about privacy or rights requests. Do not send sensitive personal information that is unnecessary for your request.</p></section>
  </InfoPage>;
}
