export const guides = [
  {
    slug: 'first-puzzle',
    ko: { title: '첫 20피스: 두 조각을 바꾸며 조작 익히기', summary: '두 조각만 바뀐 실습에서 클릭과 이동 횟수를 익힌 뒤, 실제 사진 퍼즐로 넘어갑니다.', sections: [
      ['1. 사진과 조각 수를 먼저 정하세요', '테마별 퍼즐에서 산과 호수를 선택하면 사진을 다시 검색할 필요가 없습니다. 정사각형 교환과 20피스를 선택한 뒤 ‘버전 1 시작하기’를 누르세요. 20피스는 가로 5칸, 세로 4칸입니다. 번호나 모양으로 답을 주는 게임이 아니므로 원본에서 오두막의 위치를 먼저 기억해두면 좋습니다.'],
      ['2. 옮길 조각, 바꿀 조각을 차례로 누르세요', '첫 조각을 누르면 선택 표시가 생기고, 두 번째 조각을 누르면 두 자리가 서로 바뀝니다. 빈칸으로 밀어 넣는 방식이 아닙니다. 첫 조각을 다시 누르면 선택이 취소됩니다. 이 페이지의 실습은 동작을 쉽게 확인하도록 처음 두 조각만 바꾸어 두었으며, 실제 게임은 시작할 때마다 전체를 섞습니다.'],
      ['3. 진행률은 맞는 위치의 비율입니다', '정사각형 교환은 한 번의 교환을 이동 1회로 셉니다. 두 조각이 모두 제자리로 가면 진행률이 오르고, 맞던 조각을 다른 곳으로 옮기면 내려갈 수 있습니다. 이동 횟수가 늘어도 반드시 정답에 가까워지는 것은 아닙니다.'],
      ['4. 원본 보기와 다시 섞기를 구분하세요', '‘원본 보기’는 퍼즐 위에 작은 참고 사진을 띄웁니다. 맞추려는 영역을 확인한 뒤 ‘원본 숨기기’로 닫으세요. ‘다시 섞기’는 조각을 새로 섞고 이동 횟수를 초기화하므로 힌트 버튼처럼 누르지 마세요.'],
      ['5. 직소 모드에서는 조각함을 사용합니다', '버전 2는 조각함에서 조각을 고른 다음 빈 홈을 누르거나 끌어다 놓습니다. 색과 굴곡이 맞는 원래 자리에만 고정됩니다. 틀린 홈에 놓으면 조각함에 남고 그 시도도 이동 횟수에 포함됩니다. 휴대폰에서는 끌기보다 조각과 홈을 차례로 누르는 방식을 먼저 시도해보세요.'],
    ] },
    en: { title: 'Your first 20 pieces: learn a two-tile swap', summary: 'Learn selection and move counting with two misplaced tiles, then continue to a full photo puzzle.', sections: [
      ['1. Choose the photo and piece count', 'Open Mountain lake in Collections to use a photo without searching. Choose Square swap and 20 pieces, then Start Version 1. The board has five columns and four rows. The full game does not number the answers, so first remember where the cabin sits in the original.'],
      ['2. Select one tile, then the other', 'The first click highlights a tile. The second exchanges its position with another tile; this is not a sliding game with an empty square. Click the selected tile again to cancel. The exercise below swaps only the first two pieces to make the action clear. A full game shuffles the entire board when you start.'],
      ['3. Progress measures correct positions', 'One completed swap counts as one move. Progress rises when pieces reach their original positions, but it can fall if you move a correct piece away. A higher move count does not necessarily mean you are closer to finishing.'],
      ['4. Separate Original from Shuffle again', 'Original Show opens a small reference over the board. Check the region you need, then hide it. Shuffle again starts a new arrangement and resets the move count; it is not a hint button.'],
      ['5. Shape fit uses a piece tray', 'In Version 2, select a tray piece and then a space, or drag the piece into place. It only stays in its original matching space. A wrong attempt leaves the piece in the tray and still counts as a move. On a phone, try tapping the piece and space instead of dragging.'],
    ] },
  },
  {
    slug: 'image-choice',
    ko: { title: '사진 세 장으로 배우는 퍼즐 이미지 선택', summary: '호수·숲·도시의 실제 사진을 비교하며 색의 수보다 경계와 기준점이 중요한 이유를 알아봅니다.', sections: [
      ['호수: 시작할 사물이 하나 있는 사진', '산과 호수 사진의 오른쪽 오두막은 갈색 벽과 회색 지붕이 뚜렷합니다. 처음에는 산 전체보다 이 작은 건물을 찾는 편이 후보를 줄이기 쉽습니다. 입문 사진은 이런 기준점이 적어도 하나 있고, 그 주변이 다른 색이나 질감으로 구분되는지 살펴보세요.'],
      ['숲: 색은 풍부해도 단서가 반복되는 사진', '햇살 드는 숲은 초록과 갈색이 많지만 나무줄기와 잎이 반복됩니다. 예쁜 사진이 곧 쉬운 퍼즐은 아닙니다. 아래쪽 흙길처럼 반복이 끊기는 영역이 보이면 그곳부터 시작할 수 있습니다. 선택 전에 ‘서로 구별되는 부분 세 곳’을 손으로 가리켜보세요. 세 곳을 찾기 어렵다면 조각 수를 줄이는 것이 좋습니다.'],
      ['도시: 큰 형태와 작은 무늬가 함께 있는 사진', '도시 스카이라인에는 작은 창문이 많지만 하늘과 수면, 건물의 높이가 큰 기준점이 됩니다. 20피스에서는 큰 건물 덩어리로도 위치를 찾을 수 있고, 120피스에서는 창문 간격과 벽면의 그림자까지 보게 됩니다. 한 사진을 여러 난이도로 즐기려면 이처럼 큰 단서와 작은 단서가 함께 있는 구도를 골라보세요.'],
      ['선택 전에 실제 플레이 영역을 확인하세요', '검색 카드의 미리보기와 게임의 4:3 화면은 잘리는 부분이 다를 수 있습니다. 중요한 사물이 사진 끝에 걸쳐 있다면 게임에서 보이는지 원본 보기로 확인하세요. 테마별 해설의 관찰 사진은 게임과 같은 4:3 영역을 사용합니다.'],
      ['검색이 어긋나면 주제를 좁히세요', '추상적인 감정보다 ‘호숫가 나무 오두막’처럼 보이는 사물을 적어보세요. 인물 이름만으로 해당 인물이 나오는 것은 아닙니다. 검색 실패 안내가 나오면 대체 사진이 원하는 장소·계절인지 다시 확인하거나, 사진이 정해진 테마별 퍼즐을 이용하세요.'],
    ] },
    en: { title: 'Choose a puzzle photo by comparing three scenes', summary: 'Compare a lake, forest, and skyline to see why boundaries and anchors matter more than the number of colors.', sections: [
      ['Lake: one recognizable starting object', 'The cabin on the right of Mountain lake has a brown wall and gray roof. Searching for that small building can narrow the candidates more easily than assembling the entire mountain. For a first photo, look for at least one such anchor that differs from its surroundings in color or texture.'],
      ['Forest: rich color with repeated clues', 'Sunlit forest has many greens and browns, but its trunks and leaves repeat. A beautiful picture is not automatically an easy puzzle. The dirt path interrupts that repetition and provides a starting point. Before choosing, point to three regions you can tell apart. If that is difficult, use fewer pieces.'],
      ['City: large shapes and fine patterns together', 'The skyline has small windows, yet sky, water, and building heights give large anchors. At 20 pieces, building groups can be enough; at 120, window spacing and wall shadows matter. Choose a picture with both scales of clues if you want to replay it at several difficulties.'],
      ['Check the actual playing area', 'A search card and the 4:3 game board may crop the photo differently. If an important subject sits at the edge, use Original to check what the game shows. Study photographs in Collections use the same 4:3 crop as their games.'],
      ['Make an unclear search more concrete', 'Describe visible objects, such as “wooden cabin beside a lake,” rather than only a mood. A person’s name does not guarantee that person appears. If search fails, check whether fallback photos match the intended place or season, or use a fixed photograph from Collections.'],
    ] },
  },
  {
    slug: 'piece-count',
    ko: { title: '같은 사진으로 20·48·120피스 비교하기', summary: '사진과 크기를 고정한 격자 비교로 조각 수가 실제 관찰 단서를 어떻게 바꾸는지 확인합니다.', sections: [
      ['20피스: 가로 5칸 × 세로 4칸', '오두막이나 큰 산의 형태가 한두 조각에 함께 남습니다. 한 조각에 색이 여러 개 들어가므로 배경과 사물의 관계를 보기 쉽습니다. 화면이 작거나 교환 규칙을 처음 배울 때 좋은 출발점입니다. 아래 격자는 답을 섞기 전의 구획이며 실제 게임에서는 이 구획들이 섞입니다.'],
      ['48피스: 가로 8칸 × 세로 6칸', '지붕과 벽이 여러 조각으로 나뉘어 경계선을 이어야 합니다. 같은 사진에서도 ‘오두막 전체’가 아니라 ‘지붕 오른쪽 끝’처럼 목표를 더 작게 잡게 됩니다. 20피스를 끝냈다면 사진을 바꾸지 말고 48피스로 바꿔서 이 차이를 느껴보세요.'],
      ['120피스: 가로 12칸 × 세로 10칸', '큰 사물이 없는 물이나 하늘 조각이 늘어납니다. 비슷한 회색 조각이라도 구름의 흐릿함과 물결의 가로선이 다릅니다. 화면에 충분한 크기로 표시할 수 있을 때 시도하고, 조각을 구별하기 어렵다면 80 또는 48피스로 돌아가세요.'],
      ['200·400피스 전에 확인할 것', '현재 게임은 진행을 저장하지 않습니다. 새로고침이나 페이지 이동을 하면 이어서 할 수 없으므로 긴 퍼즐을 시작하기 전에 이 점을 고려하세요. 조각 수만으로 완성 시간을 약속할 수는 없습니다. 사진의 반복 무늬, 화면 크기, 선택한 모드에 따라 필요한 시간이 달라집니다.'],
      ['비교할 때 한 가지 조건만 바꾸세요', '사진·모드·화면 크기를 고정하고 조각 수만 바꾸면 어느 지점부터 단서가 작아지는지 알 수 있습니다. 사진과 모드를 동시에 바꾸면 어려워진 이유가 조각 수인지 다른 조건인지 구분하기 어렵습니다. 완성 시간보다 ‘어떤 영역에서 원본을 다시 봤는지’를 비교해보세요.'],
    ] },
    en: { title: 'Compare 20, 48, and 120 pieces on one photo', summary: 'Keep the photograph fixed and see how smaller pieces change the clues you can use.', sections: [
      ['20 pieces: five columns by four rows', 'A cabin or mountain shape can remain visible within just a few tiles. Each piece includes more colors and context, making it easier to relate subject and background. This is a useful starting point on a small screen or while learning the controls. The diagrams show the unshuffled divisions; the actual game mixes them.'],
      ['48 pieces: eight columns by six rows', 'The roof and wall split across more pieces, so you must connect their boundaries. Your target changes from “the cabin” to “the right end of the roof.” After completing 20 pieces, keep the same photo and try 48 to feel this change.'],
      ['120 pieces: twelve columns by ten rows', 'More tiles contain only water or sky. Similar gray pieces may differ through soft clouds or horizontal ripples. Try this when your screen can display enough detail; return to 80 or 48 if pieces become hard to distinguish.'],
      ['Before choosing 200 or 400', 'The current game does not save progress. Refreshing or leaving the page means starting over, which matters for a longer puzzle. Piece count alone cannot predict completion time: repeated textures, screen size, and mode all affect the experience.'],
      ['Change only one condition at a time', 'Keep the photograph, mode, and screen size fixed while increasing the piece count. Changing everything at once makes it difficult to tell why the puzzle became harder. Compare which regions made you consult the reference rather than focusing only on finishing time.'],
    ] },
  },
  {
    slug: 'focus-routine',
    ko: { title: '막힌 조각을 찾는 세 가지 실제 상황', summary: '반사, 반복되는 줄기, 비슷한 창문 때문에 막혔을 때 관찰 기준을 바꾸는 방법입니다.', sections: [
      ['상황 1: 회색 조각이 산인지 반사인지 모르겠어요', '산과 호수 퍼즐의 원본을 열고 물가의 높이를 먼저 확인하세요. 후보 조각에 잔물결처럼 가로로 끊기는 선이 있으면 아래쪽 반사와 비교합니다. 산의 능선처럼 굵고 불규칙한 경계가 있으면 위쪽 산과 비교합니다. 색을 한 번 더 보는 대신 선이 끊기는 방향을 바꾸어 읽는 연습입니다.'],
      ['상황 2: 나무줄기가 모두 비슷해 보여요', '햇살 드는 숲에서 이미 맞춘 줄기 하나를 고릅니다. 그 줄기의 폭과 어느 쪽 면이 밝은지 기억한 뒤 바로 위나 아래에 들어갈 조각만 찾으세요. 색은 맞지만 굵기가 갑자기 변하면 다른 나무일 수 있습니다. 후보 범위를 한 줄기의 이웃으로 줄이는 것이 핵심입니다.'],
      ['상황 3: 창문 격자가 계속 틀려요', '도시 퍼즐에서는 창문에서 지붕으로 시선을 옮겨보세요. 건물 꼭대기는 높이와 각도가 달라 창문보다 구별하기 쉽습니다. 지붕 하나를 고정하고 그 아래 벽면의 밝기가 이어지는지 보세요. 창문 선 하나가 이어진다고 확정하지 말고 건물의 바깥 윤곽도 함께 확인합니다.'],
      ['조작이 막힌 것인지 단서가 막힌 것인지 확인하세요', '정사각형 교환은 조각 두 개를 눌러야 움직이며, 같은 조각을 두 번 누르면 취소됩니다. 직소는 조각함의 조각을 먼저 고른 다음 빈 홈을 누릅니다. 클릭 순서가 맞는데 놓이지 않으면 이미지와 굴곡이 맞는 원래 자리인지 다시 확인하세요.'],
      ['다시 시작할 때 남길 메모 한 줄', '‘어려웠다’ 대신 ‘물과 산을 색으로만 구분해서 헷갈렸다’처럼 단서를 적어보세요. 다음 판에서는 바로 그 단서부터 바꿔 시도할 수 있습니다. 피곤하거나 화면이 너무 작다면 쉬거나 조각 수를 낮추세요. 퍼즐은 속도 경쟁이나 집중력 진단 도구가 아닙니다.'],
    ] },
    en: { title: 'Three practical ways out of a stuck puzzle', summary: 'Change your clue when reflections, repeating trunks, or similar windows leave you guessing.', sections: [
      ['Situation 1: mountain or reflection?', 'Open the lake reference and locate the shoreline. Compare horizontally interrupted gray pieces with ripples below it. Compare bold, irregular boundaries with the mountain above it. Instead of checking the same color again, change the direction of the lines you are studying.'],
      ['Situation 2: every trunk looks alike', 'Choose one forest trunk you have already placed. Remember its width and illuminated side, then search only for the piece immediately above or below it. A sudden width change can indicate a different tree even if the color matches. Narrow the task to one neighbor.'],
      ['Situation 3: window grids keep misleading you', 'Move your attention from windows to rooftops. Their heights and angles differ more clearly. Anchor one roof and check the brightness of the wall beneath it. A continuous window line is not enough; check the outside contour of the building too.'],
      ['Is it a control problem or a clue problem?', 'Square swap needs two different tile selections; clicking the same tile twice cancels the selection. Shape fit needs a tray piece first and a space second. If the click order is right but the piece will not stay, compare both its image and outline with its original location.'],
      ['Keep one useful note for next time', 'Instead of “that was difficult,” note “I confused water and mountains by using color alone.” Next time, begin by changing that specific clue. Rest or reduce the count if you are tired or the screen is too small. Puzzly is not a speed contest or a test of your ability to concentrate.'],
    ] },
  },
  {
    slug: 'anchor-system',
    ko: { title: '여섯 장의 사진으로 익히는 네 가지 기준점', summary: '색 영역·경계선·고유 형태·반복의 예외를 실제 컬렉션 사진에서 찾는 관찰 순서입니다.', sections: [
      ['1. 넓은 색 영역은 후보를 나누는 첫 단계입니다', '해변에서는 하늘·바다·모래, 도시에서는 하늘·수면·건물이 큰 층을 이룹니다. 이 단계의 목적은 정답을 확정하는 것이 아니라 후보를 위·가운데·아래처럼 나누는 것입니다. 비슷한 색이 다른 영역에도 나타날 수 있으므로 색만으로 자리를 결정하지 말고 다음 단서를 찾을 범위를 줄이는 데 사용하세요.'],
      ['2. 경계선의 방향으로 조각의 순서를 좁힙니다', '호수의 물가는 거의 수평이고, 해변의 포말은 굽으며, 케이크의 윗면은 타원형입니다. 같은 흰색이나 회색 조각이라도 선이 곧은지, 어느 방향으로 휘는지, 선 양쪽의 질감이 무엇인지 비교하면 이웃 조각을 정할 수 있습니다. 경계가 화면 끝에서 어디로 나가는지도 함께 보세요.'],
      ['3. 고유 형태는 가장 먼저 고정할 기준점입니다', '호수의 오두막, 여우의 귀와 코, 도시의 서로 다른 지붕처럼 한 번만 등장하는 형태를 찾습니다. 고유 형태 하나를 완성하면 그 주변 조각은 전체 사진이 아니라 해당 사물의 이웃과만 비교하면 됩니다. 다만 눈에 띈다는 이유로 사진 중앙에 있다고 가정하지 말고 원본에서 정확한 위치를 확인하세요.'],
      ['4. 반복 무늬에서는 예외를 찾습니다', '숲의 나무줄기, 도시의 창문, 케이크의 크림은 비슷한 모양이 반복됩니다. 이때 모든 반복을 한꺼번에 맞추려 하지 말고 굵기가 다른 줄기, 높이가 다른 지붕, 일부가 가려진 장식처럼 반복이 깨지는 지점을 찾으세요. 예외 하나를 고정한 뒤 바로 옆 반복을 순서대로 연결하는 편이 안정적입니다.'],
      ['5. 단서가 충돌하면 두 조건이 함께 맞는지 봅니다', '색은 맞지만 선이 끊기거나, 모양은 이어지지만 빛의 방향이 바뀌면 아직 근거가 부족합니다. 최소 두 가지 조건이 동시에 맞을 때 위치를 유지하세요. 예를 들어 여우 몸통의 주황색뿐 아니라 등의 윤곽까지, 해변의 흰색뿐 아니라 포말의 굽은 방향까지 확인하는 방식입니다.'],
    ] },
    en: { title: 'Four anchor types across six photographs', summary: 'Use broad color, boundaries, unique shapes, and breaks in repetition in a consistent order.', sections: [
      ['1. Broad color is a first division, not a final answer', 'Beach separates into sky, sea, and sand; skyline separates into sky, water, and buildings. Use those regions to divide candidates into broad positions. Similar colors can appear elsewhere, so color should narrow the search rather than prove a location.'],
      ['2. Boundary direction narrows the order', 'The lake shoreline is nearly horizontal, beach foam bends, and the cake rim forms an oval. Compare whether a line is straight or curved, where it turns, and the texture on both sides. Also notice where a boundary leaves the edge of a tile.'],
      ['3. A unique shape becomes the first anchor', 'The cabin, the fox ears and nose, and distinct rooftops occur only once. Once such a shape is placed, neighboring pieces need to be compared only with that object. Do not assume a prominent subject is centered; confirm its actual position in the original.'],
      ['4. Find the break inside repetition', 'Forest trunks, window grids, and cream swirls repeat. Look for the different trunk width, roof height, or partly hidden decoration that interrupts the pattern. Fix one exception, then connect its immediate neighbors in order.'],
      ['5. Keep a placement when two clues agree', 'Matching color with a broken line, or matching shape with reversed light, is weak evidence. Keep a position when at least two conditions agree: orange fur plus the back contour, or white foam plus the direction of its curve.'],
    ] },
  },
  {
    slug: 'mobile-play',
    ko: { title: '휴대폰에서 사진 퍼즐을 편하게 조작하는 순서', summary: '작은 화면에서 사진·조각 수·탭 조작을 조정하고 중단 위험을 줄이는 실제 이용 안내입니다.', sections: [
      ['1. 세로 화면에서는 12~30피스로 조작부터 확인하세요', '휴대폰에서는 같은 조각 수도 각 조각의 표시 면적이 작습니다. 첫 판은 12피스나 20피스로 시작해 선택 표시와 원본 보기 버튼의 위치를 확인하세요. 30피스에서 경계선이 보인다면 그대로 올리고, 손가락으로 원하는 조각을 안정적으로 선택하기 어렵다면 사진을 바꾸기보다 먼저 조각 수를 낮추세요.'],
      ['2. 정사각형 교환은 끌지 말고 두 번 탭합니다', '버전 1에서는 옮길 조각을 한 번 탭하고, 바꿀 위치를 다시 탭합니다. 첫 조각에 선택 표시가 생겼는지 확인한 뒤 화면을 스크롤하세요. 같은 조각을 다시 탭하면 선택이 취소되므로 반응이 없다고 빠르게 연속 탭하지 않는 편이 좋습니다.'],
      ['3. 직소 모드는 조각과 홈을 차례로 선택할 수 있습니다', '작은 조각을 길게 끌기 어렵다면 조각함에서 한 조각을 탭한 뒤 왼쪽의 빈 홈을 탭하세요. 맞는 자리라면 고정되고, 틀리면 조각함에 남습니다. 조각함 안에서 스크롤할 때는 조각 중앙보다 빈 여백에서 손가락을 움직이면 의도치 않은 선택을 줄일 수 있습니다.'],
      ['4. 작은 화면에는 큰 기준점이 있는 사진이 유리합니다', '여우처럼 주제가 한 개이거나 호수처럼 오두막이 있는 사진은 축소해도 출발점을 찾기 쉽습니다. 숲의 반복되는 줄기나 케이크의 작은 장식은 조각 수가 많을수록 구분하기 어렵습니다. 사진 카드에서 기준점 세 곳을 말할 수 있는지 확인한 뒤 시작하세요.'],
      ['5. 새로고침과 페이지 이동 전에 현재 판을 마치세요', '퍼즐 진행은 서버 계정에 저장되지 않습니다. 전화 수신이나 다른 앱 전환 자체는 판을 지우지 않지만, 브라우저가 페이지를 새로 불러오거나 탭을 닫으면 이어서 할 수 없습니다. 긴 120피스 이상은 안정적인 화면과 시간을 확보한 뒤 선택하고, 이동 중에는 짧은 판을 권합니다.'],
    ] },
    en: { title: 'A practical order for playing on a phone', summary: 'Adjust photo, count, and tap controls for a smaller screen and reduce the risk of losing a long puzzle.', sections: [
      ['1. Confirm the controls with 12–30 pieces', 'Each piece occupies less screen area on a phone. Begin with 12 or 20 pieces and locate selection feedback and the Original control. Increase the count only while boundaries remain visible; if tapping becomes unreliable, reduce the count before changing the photograph.'],
      ['2. Square swap uses two taps, not a drag', 'Tap the piece to move, then tap its destination. Confirm the first selection highlight before scrolling. Tapping the same tile again cancels it, so avoid rapid repeated taps when waiting for visual feedback.'],
      ['3. Shape fit also supports tap then space', 'If dragging a small piece is awkward, tap it in the tray and then tap the empty space. A correct piece stays; a wrong one remains in the tray. Scroll from tray padding rather than directly over a piece to reduce accidental selection.'],
      ['4. Choose photographs with large anchors', 'A single fox or a lake cabin remains recognizable when reduced. Repeating forest trunks and small cake decorations become harder at high counts. Before starting, check whether you can name three distinct anchors in the card.'],
      ['5. Finish before a reload or navigation', 'Progress is not stored in an account. Switching apps alone does not intentionally reset the board, but a browser reload or closed tab does. Reserve 120 pieces and above for a stable screen and enough time; use a shorter puzzle while moving.'],
    ] },
  },
  {
    slug: 'compare-sessions',
    ko: { title: '같은 사진 두 판을 비교하는 간단한 기록법', summary: '완성 시간 대신 출발점·원본 확인·막힌 영역을 기록해 자신에게 맞는 풀이법을 찾습니다.', sections: [
      ['1. 사진·모드·조각 수를 먼저 고정하세요', '두 판을 비교할 때는 한 번에 한 조건만 바꿉니다. 예를 들어 산과 호수 48피스 정사각형 교환을 두 번 진행하고, 첫 판은 오두막에서, 둘째 판은 물가에서 시작합니다. 사진과 조각 수까지 바꾸면 어느 선택이 차이를 만들었는지 알기 어렵습니다.'],
      ['2. 시작 전에 첫 기준점을 한 줄로 적습니다', '‘오두막 지붕부터’, ‘포말의 가장 긴 곡선부터’처럼 실제로 찾을 형태를 기록하세요. ‘쉬운 부분부터’는 나중에 무엇을 했는지 확인하기 어렵습니다. 첫 기준점을 맞춘 뒤 그 주변으로 확장했는지도 함께 적으면 전략을 반복할 수 있습니다.'],
      ['3. 원본을 본 이유만 표시합니다', '원본을 열 때마다 횟수를 세기보다 이유를 짧게 적습니다. ‘수평선 높이’, ‘여우 다리 간격’, ‘케이크 앞뒤 장식’처럼 기록하면 자주 놓치는 단서 유형이 보입니다. 원본을 적게 보는 것이 목표가 아니라, 같은 이유로 반복해서 막히는지를 확인하는 과정입니다.'],
      ['4. 마지막에 남은 영역을 비교합니다', '완성 직전까지 남은 조각은 사진의 어려운 부분을 보여줍니다. 호수의 회색 산과 반사, 숲의 초록 잎, 케이크의 반복 크림처럼 마지막 영역을 기록하세요. 다음 판에서는 그 영역을 초반에 처리해 남은 조각이 달라지는지 확인합니다.'],
      ['5. 이동 횟수는 같은 모드 안에서만 참고합니다', '정사각형 교환은 두 조각의 교환을 한 번으로 세고, 직소 모드는 틀린 배치 시도도 이동에 포함합니다. 두 모드의 숫자를 직접 비교하지 마세요. 이 기록은 능력을 평가하기 위한 점수가 아니라 자신에게 유용한 시각 단서를 찾기 위한 메모입니다.'],
    ] },
    en: { title: 'A simple record for comparing two sessions', summary: 'Track the starting anchor, reference checks, and last unresolved area instead of treating completion time as the only result.', sections: [
      ['1. Hold photo, mode, and count constant', 'Change one condition at a time. Play Mountain lake at 48-piece Square swap twice, beginning with the cabin in one session and the shoreline in the other. Changing the image and count at the same time hides which choice mattered.'],
      ['2. Write one precise starting anchor', 'Use “cabin roof first” or “longest foam curve first,” not “easy part first.” Note whether you expanded from that anchor after placing it. A concrete phrase makes the strategy repeatable.'],
      ['3. Record why you opened the original', 'Instead of chasing the lowest number of checks, note the reason: “shoreline height,” “spacing between fox legs,” or “front and back cake decorations.” Repeated reasons reveal the clue type you tend to miss.'],
      ['4. Compare the last unresolved region', 'Tiles left near the end reveal the difficult part: gray mountain and reflection, repeated leaves, or similar cream swirls. In the next session, address that region early and see whether a different area remains.'],
      ['5. Compare move counts only within one mode', 'Square swap counts exchanges; Shape fit includes incorrect placement attempts. Do not compare those totals directly. This record is not a score of ability; it is a way to find visual evidence that works for you.'],
    ] },
  },
] as const;
