import type { Metadata } from 'next';
import { InfoPage } from '../components/info-page';
export const metadata: Metadata={title:'개인정보처리방침',description:'퍼즐리의 개인정보 처리, 외부 이미지, 쿠키 및 광고 관련 안내입니다.',alternates:{canonical:'/privacy'}};
export default function Page(){return <InfoPage path="/privacy" eyebrow="PRIVACY" title="개인정보처리방침" intro="퍼즐리는 필요한 정보만 최소한으로 다루며, 방문자가 서비스의 데이터 흐름을 이해할 수 있도록 공개합니다. 시행일: 2026년 10월 6일">
<section><h2>1. 수집하는 개인정보</h2><p>퍼즐리는 회원가입 기능을 제공하지 않으며 이름, 전화번호, 주소 등의 개인정보를 직접 입력받아 서버에 저장하지 않습니다. 사용자가 입력한 이미지 검색어는 이미지 추천을 위해 일시적으로 처리되지만 퍼즐리의 사용자 계정이나 데이터베이스에 저장하지 않습니다. 진행 중인 조각 위치는 브라우저에서만 처리됩니다. 퍼즐을 완성한 경우 전체 순위 제공을 위해 무작위 브라우저 식별값을 일방향 해시한 값, 퍼즐 모드, 피스 수, 사진 식별값과 제목, 시작·완성 시각, 완성 시간 및 이동 횟수를 저장합니다.</p></section>
<section><h2>2. 자동으로 전달될 수 있는 정보</h2><p>사이트 접속 과정에서 호스팅 제공자 또는 외부 콘텐츠 제공자에게 IP 주소, 브라우저 종류, 접속 시각, 요청한 주소와 같은 일반적인 접속 정보가 전달될 수 있습니다. 이는 보안, 장애 대응, 이미지 제공 등 각 서비스의 운영 목적에 따라 처리될 수 있습니다.</p></section>
<section><h2>3. Vercel Web Analytics</h2><p>퍼즐리는 방문자 수와 페이지 조회 흐름을 파악하기 위해 Vercel Web Analytics를 사용합니다. 이 도구는 쿠키 없이 일별로 갱신되는 요청 기반 식별값을 사용하며, 방문자 개인을 식별하거나 사이트 간 행동을 추적하지 않는 집계 통계를 제공합니다. 페이지 경로, 유입 경로, 국가, 운영체제, 브라우저, 기기 유형 등의 집계 정보가 Vercel 프로젝트 대시보드에 표시될 수 있습니다. 검색어, 이메일, 계정 정보와 같은 개인 식별 정보를 분석 이벤트에 별도로 전송하지 않습니다.</p></section>
<section><h2>4. 외부 이미지 서비스</h2><p>추천 이미지는 Pexels의 검색 API와 운영팀이 사전에 선별한 Unsplash 이미지에서 제공됩니다. 사용자가 검색을 실행하면 검색어가 퍼즐리 서버를 거쳐 Pexels에 전달되며, 이미지를 표시할 때 Pexels 또는 Unsplash 서버로 이미지 요청이 전송될 수 있습니다. 각 제공처의 개인정보처리방침이 적용될 수 있으며 퍼즐리는 외부 사이트의 데이터 처리 방식을 통제하지 않습니다.</p></section>
<section><h2>5. 쿠키와 광고 서비스</h2><p>퍼즐리는 Google AdSense와 카카오 애드핏(Kakao AdFit)의 사이트 확인 및 광고 게재 스크립트를 사용합니다. Google, Kakao 및 각 광고 파트너는 광고 제공, 노출·클릭 측정, 부정 이용 방지와 맞춤 광고 제공을 위해 쿠키 또는 유사 기술을 사용하고 IP 주소, 브라우저 정보, 광고 식별 정보, 접속·광고 이용 기록 등을 처리할 수 있습니다. 퍼즐리 자체는 퍼즐 진행을 위해 별도의 필수 쿠키를 설정하지 않습니다.</p><p>Google 광고 설정은 <a href="https://adssettings.google.com/" target="_blank" rel="noreferrer">Google 광고 설정</a>에서 관리하거나 사용 중지할 수 있으며, 제3자 사업자의 맞춤 광고 쿠키는 <a href="https://www.aboutads.info/choices/" target="_blank" rel="noreferrer">AboutAds 선택 페이지</a>에서 관리할 수 있습니다. 카카오 광고 관련 처리 내용과 이용자 선택 방법은 <a href="https://kakao.com/policy/privacy" target="_blank" rel="noreferrer">카카오 개인정보처리방침</a> 및 <a href="https://adfit.kakao.com/" target="_blank" rel="noreferrer">카카오 애드핏</a>에서 확인할 수 있습니다.</p></section>
<section><h2>6. 순위 기록, 보유 기간과 삭제</h2><p>순위표는 이름이나 계정 대신 브라우저에 생성한 무작위 식별값의 해시와 짧은 참가자 코드만 사용합니다. 같은 모드와 피스 수에서는 한 브라우저의 최고 기록만 순위에 표시됩니다. 시작 후 완성되지 않은 기록은 1일, 완성된 순위 기록은 최대 1년간 보관한 뒤 삭제할 수 있습니다. 브라우저 식별값은 로컬 저장소에 보관되며 사이트 데이터를 삭제하면 새 값이 생성됩니다. 호스팅 및 외부 서비스의 접속 기록은 각 제공자의 보유 정책에 따라 관리됩니다.</p></section>
<section><h2>7. 아동의 개인정보</h2><p>퍼즐리는 연령을 확인하거나 아동의 개인정보를 의도적으로 수집하지 않습니다. 보호자는 아동이 외부 링크나 이미지 제공 서비스를 이용할 때 함께 확인해주시기 바랍니다.</p></section>
<section><h2>8. 방침 변경과 문의</h2><p>기능 또는 법령 변경에 따라 본 방침이 수정될 수 있으며 시행일을 갱신하여 알립니다. 개인정보 및 권리 관련 문의는 <a href="mailto:daehoon1027@gmail.com">daehoon1027@gmail.com</a>을 이용해 주세요. 문의 처리에 불필요한 민감한 개인정보는 보내지 마세요.</p></section></InfoPage>}
